[rules]
missing-license = {level = "off", source-shasum = "b28c91532a8b65a1f983b4c28b7488174e4a01008e29ce8e69bd789f28bc2a89"}
unused-dependency = {level = "off"}
unused-runpath-entry = {level = "off"}
library-dependency-not-found = { level = "off" }
empty-top-level-directory = {level = "off"}
