[rules]
missing-license = {level = "off", source-shasum = "a8f84a39918ec6415ce765d9b429d313ba97b8143169c172e734b9514464f5b2"}
unused-dependency = {level = "off"}
unused-runpath-entry = {level = "off"}
library-dependency-not-found = { level = "off" }
empty-top-level-directory = {level = "off"}
