[rules]
missing-license = {level = "off", source-shasum = "967311f84955316969bdb1d8d4b983718ef42338639c621ec4c34fddef355e99"}
unused-dependency = {level = "off"}
unused-runpath-entry = {level = "off"}
library-dependency-not-found = { level = "off" }
empty-top-level-directory = {level = "off"}
