[rules]
# Ignore sample scripts
host-script-interpreter = {ignored_files = ["share/**/*.sample"]}
license-not-found = {level = "off", source-shasum = "429dc0f5fe5f14109930cdbbb588c5d6ef5b8528910f0d738040744bebdc6275"}
missing-license = {level = "off", source-shasum = "429dc0f5fe5f14109930cdbbb588c5d6ef5b8528910f0d738040744bebdc6275"}
# These packages are needed are runtime
unused-dependency = {ignored_packages = ["core/{gettext,sed,cacerts,openssh,gcc-libs}"]}
unused-runpath-entry = {level = "off"}
missing-script-interpreter-dependency = {level = "off"}
