[rules]
# Ignore sample scripts
host-script-interpreter = {ignored_files = ["share/**/*.sample"]}
license-not-found = {level = "off", source-shasum = "0842dc384a23ac33ba3e570c4f3a8ded85963ee4713b1cd21153c3db41813d1e"}
missing-license = {level = "off", source-shasum = "0842dc384a23ac33ba3e570c4f3a8ded85963ee4713b1cd21153c3db41813d1e"}
# These packages are needed are runtime
unused-dependency = {ignored_packages = ["core/{gettext,sed,cacerts,openssh,gcc-libs,rust}"]}
unused-runpath-entry = {level = "off"}
missing-script-interpreter-dependency = {level = "off"}
