[rules]
# ignore examples with host script interpreters
host-script-interpreter = {ignored_files = ["*-example.{bash,tcsh}"]}
license-not-found = {level = "off", source-shasum = "e596083744e746be7d2823b62b43f4418dd7bf56303b4dc09e6fe8112fe3d7ed"}
missing-license = {level = "off", source-shasum = "e596083744e746be7d2823b62b43f4418dd7bf56303b4dc09e6fe8112fe3d7ed"}
unused-runpath-entry = {level = "off"}
