name: Trigger Enterprise Build

on:
  push:
    branches:
      - base-2025

jobs:
  trigger-enterprise-build:
    uses: habitat-sh/enterprise-packages/.github/workflows/build-packages.yml
    with:
      foundational_ref: ${{ github.sha }}
    secrets: inherit
